"use client";

import { useState } from "react";
import { Upload, Lock } from "lucide-react";
import Image from "next/image";



interface UploadPageProps {
  onUploadComplete: (data: any) => void;
}

export function UploadPage({ onUploadComplete }: UploadPageProps) {
  const [file, setFile] = useState<File | null>(null);
  const [password, setPassword] = useState("");
  const [isUploading, setIsUploading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      setError(null);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file) {
      setError("Please select a PDF file");
      return;
    }

    setIsUploading(true);
    setError(null);

    try {
      const { fetchStatement } = await import("@/lib/api");
      const data = await fetchStatement(file, password || null);
      onUploadComplete(data);
    } catch (err: any) {
      setError(err.response?.data?.detail || "Failed to process statement. Please try again.");
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-green-50 via-white to-green-50 dark:from-green-950/20 dark:via-black dark:to-green-950/20">
      <div className="w-full max-w-md space-y-8 p-8">
        {/* mpesa logo */}
        <div className="text-center space-y-2">
          <div className="flex items-center justify-center mb-4">
            <div className="w-16 h-16 rounded-full flex items-center justify-center">
           
              <Image
                src="/mpesa.png"
                alt="M-PESA Logo"
                width={40}
                height={40}
              />
            </div>
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 dark:text-white">
            M-PESA Wrapped
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-400">
            Discover your money story
          </p>
        </div>

      
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* upload file */}
          <div className="space-y-2">
            <label
              htmlFor="file-upload"
              className="flex flex-col items-center justify-center w-full h-48 border-2 border-dashed rounded-lg cursor-pointer bg-white dark:bg-gray-900 border-gray-300 dark:border-gray-700 hover:border-green-500 dark:hover:border-green-500 transition-colors"
            >
              <div className="flex flex-col items-center justify-center pt-5 pb-6">
                <Upload className="w-12 h-12 mb-3 text-gray-400" />
                <p className="mb-2 text-sm text-gray-500 dark:text-gray-400">
                  <span className="font-semibold">Click to upload</span> or drag and drop
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  M-PESA Statement PDF
                </p>
                {file && (
                  <p className="mt-2 text-sm text-green-600 dark:text-green-400 font-medium">
                    {file.name}
                  </p>
                )}
              </div>
              <input
                id="file-upload"
                type="file"
                className="hidden"
                accept=".pdf"
                onChange={handleFileChange}
              />
            </label>
          </div>

          {/* password => optional for statements generated by MPESA App */}
          <div className="space-y-2">
            <label htmlFor="password" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              Password (Optional)
            </label>
            <div className="relative">
              <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
              <input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                placeholder="Enter PDF password if protected.  It is delivered to you by M-PESA via SMS."
              />
            </div>
          </div>

          {/* error message */}
          {error && (
            <div className="p-4 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800">
              <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
            </div>
          )}

          {/* submit  */}
          <button
            type="submit"
            disabled={!file || isUploading}
            className="w-full py-3 px-4 bg-green-600 hover:bg-green-700 disabled:bg-gray-400 disabled:cursor-not-allowed text-white font-semibold rounded-lg transition-colors flex items-center justify-center space-x-2"
          >
            {isUploading ? (
              <>
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                <span>Processing...</span>
              </>
            ) : (
              <span>Get Your Wrapped</span>
            )}
          </button>
        </form>

        {/* privacy */}
        <p className="text-xs text-center text-gray-500 dark:text-gray-400">
          Your statement is processed securely and never stored on our servers. You can also review the source code on{" "}
          <a
            href="https://github.com/kagemanjoroge/mpesa-wrapped"
            target="_blank"
            rel="noopener noreferrer"
            className="text-green-600 hover:underline"
          >
            GitHub
          </a>.
        </p>
      </div>
    </div>
  );
}
